services:
    backend-scms:
      restart: unless-stopped
      build:
        context: ../scms-backend
        dockerfile: ../scms-deploy/api/Dockerfile
      volumes:
        - ../scms-backend:/api
        - /api/node_modules
      environment:
        DB_API_HOST: api-db
        DB_API_PORT: 5432
        DB_WEBAPP_HOST: webapp-db
        DB_WEBAPP_PORT: 5432
      ports:
        - "${API_PORT}:3000"
      networks:
        - scms_api_network
        - scms_webapp_network

    webapp-scms:
      restart: unless-stopped
      build:
        context: ../scms-webapp
        dockerfile: ../scms-deploy/webapp/Dockerfile
      volumes:
        - ../scms-webapp:/webapp
        - /webapp/node_modules
      ports:
        - "${WEBAPP_PORT}:5173"
      networks:
        - scms_webapp_network
        - scms_api_network

    webapp-db:
      image: postgres:17
      container_name: scms_webapp_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${WEBAPP_DB_USER}
        POSTGRES_PASSWORD: ${WEBAPP_DB_PASSWORD}
        POSTGRES_DB: ${WEBAPP_DB_NAME}
      ports:
        - "${WEBAPP_DB_PORT}:5432"
      volumes:
        - webapp-db-vol:/var/lib/postgresql/data
      networks:
        - scms_webapp_network

    api-db:
      image: postgres:17
      container_name: scms_api_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${API_DB_USER}
        POSTGRES_PASSWORD: ${API_DB_PASSWORD}
        POSTGRES_DB: ${API_DB_NAME}
      ports:
        - "${API_DB_PORT}:5432"
      volumes:
        - api-db-vol:/var/lib/postgresql/data
      networks:
        - scms_api_network

networks:
  scms_webapp_network: {}
  scms_api_network: {}

volumes:
  api-db-vol:
  webapp-db-vol:
  api-node-modules:
  webapp-node-modules:
